services:
  - type: web
    name: rendoor-api
    runtime: node
    rootDir: server
    buildCommand: npm ci && npm run prisma:generate && npm run prisma:push
    startCommand: npm run start
    envVars:
      - key: DATABASE_URL
        value: file:./dev.db
      - key: JWT_SECRET
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: MAIL_FROM
        sync: false
      - key: APP_URL
        value: https://reendoor.muhammadhassan.workers.dev
